apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  annotations:
    # https://github.com/helm/helm/blob/master/docs/charts_hooks.md
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook": pre-install, pre-upgrade
data:
  config.js: |
    window.REACT_APP_JIMAT_API_ROOT='$JIMAT_API_URL'
    window.REACT_APP_GOOGLE_CLIENT_ID='$GOOGLE_CLIENT_ID'
    window.NODE_ENV='{{ .Release.Namespace | replace "jx-" "" }}'

