apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  annotations:
    # https://github.com/helm/helm/blob/master/docs/charts_hooks.md
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook": pre-install, pre-upgrade
data:
  {{- if eq "jx-staging" .Release.Namespace }}
  config.js: {{ toYaml .Values.config.staging | indent 4 }}
  {{- else }}
  config.js: {{ toYaml .Values.config.production | indent 4 }}
  {{- end }}
