{{- if and (.Values.jxRequirements.ingress.domain) (not .Values.knativeDeploy) }}
apiVersion: {{ .Values.jxRequirements.ingress.apiVersion }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
    jenkins.io/host: "{{ .Values.jxRequirements.ingress.domain }}"
{{- end }}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if .Values.jxRequirements.ingress.annotations }}
{{ toYaml .Values.jxRequirements.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ .Values.service.name }}
spec:
  rules:
{{- if eq "jx-production" .Release.Namespace }}
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
    host: jimatshop.com
  - http:a
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
    host: www.jimatshop.com
{{- else}}
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/{{ .Release.Namespace }}/hook"
{{- else if .Values.jxRequirements.ingress.domain }}
    host: {{ .Values.service.name | replace "jimat-" "" }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
{{- if eq "jx-production" .Release.Namespace }}
  - hosts:
    - jimatshop.com
    - www.jimatshop.com
    secretName: "tls-jimatshop-com-p"
{{- else }}
  - hosts:
    - {{ .Values.service.name | replace "jimat-" ""  }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- if and (hasKey .Values.jxRequirements.ingress.tls "secretName") (.Values.jxRequirements.ingress.tls.secretName) }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
