---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Chart.Name }}
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  region: ap-southeast-1
  data:
    - name: GOOGLE_CLIENT_ID
      key: {{ template "environment" .Release.Namespace }}/jimat/shop
      property: GOOGLE_CLIENT_ID
    - name: JIMAT_API_URL
      key: {{ template "environment" .Release.Namespace }}/jimat/shop
      property: JIMAT_API_URL
    - name: config.js
      key: {{ template "environment" .Release.Namespace }}/jimat/shop
      property: config.js
