# Default values for your projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# optional list of image pull secrets to use to pull images
jx:
  imagePullSecrets: []

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80

# Canary deployments
# If enabled, Istio and Flagger need to be installed in the cluster
canary:
  enabled: false
  progressDeadlineSeconds: 60
  analysis:
    interval: "1m"
    threshold: 5
    maxWeight: 60
    stepWeight: 20
    # WARNING: Canary deployments will fail and rollback if there is no traffic that will generate the below specified metrics.
    metrics:
      latency:
        threshold: 500
        interval: "1m"
  # The host is using Istio Gateway or the underlying ingress mechanism
  # This value is defaulted from the environments jx-requirements.yml ingress configuration
  host: ""

service:
  name: ops-app-jimat-shop
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: ""
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: ""

# custom ingress annotations on this service
ingress:
  annotations:
    # kubernetes.io/ingress.class: nginx

serviceAccount:
  enabled: true
  name: ""
  annotations: {}
#  annotations:
#    iam.gke.io/gcp-service-account: my-sa-in-gke
  labels: {}

# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    domain: "jimathub.com"
    externalDNS: true
    namespaceSubDomain: .
    serviceType: ""
    tls:
      email: "support@mail.jimathub.com"
      enabled: true
      production: false
      secretName: "tls-jimathub-com-p"

    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "networking.k8s.io/v1beta1"

    # shared ingress annotations on all services
    annotations:
    #  kubernetes.io/ingress.class: nginx

configValues: |
  window.REACT_APP_JIMAT_API_ROOT='https://jimat-test.robugroup.com'
  window.REACT_APP_GOOGLE_CLIENT_ID='552393042714-d8dboeed2krpot6agba44ftshvk0c5r2.apps.googleusercontent.com'
  window.NODE_ENV='staging'
