# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  watch:
    types: [started]

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      # checkout to develop branch
      - name: Checkout
        uses: actions/checkout@v2
      # use nodejs ver:10
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      # =====
      - name: Install NPM dependency
        run: yarn install
      - name: Create Production Build
        env:
          REACT_APP_JIMAT_API_ROOT: ${{ secrets.JIMAT_API_ROOT }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: yarn build
      - name: View Current Directory
        run: ls -la
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: '-av --delete'
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/var/www/jimat-pwa/build'
